version: '3.8'

services:
    nginx:
        image: nginx:1.23.4-alpine
        ports:
            - '80:80'
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - database
        networks:
            - symfony_network

    symfony_app:
        container_name: symfony_app
        build:
            context: ./docker/php
        ports:
            - '9001:9001'
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - .:/var/www/app
            - ./docker/php/settings/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        restart: always
        tty: true
        working_dir: /var/www/app/symfony
        depends_on:
            - database
            - nginx
        env_file:
            - .env
        networks:
            - symfony_network


    database:
        container_name: postgres
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - data-pgsql:/var/lib/postgresql/data
            - ./docker/postgres/sql-dist/:/docker-entrypoint-initdb.d/
#            - ./docker/postgres/data/:/var/lib/postgresql/data:rw
#            - ./docker/postgres/data/:/var/lib/postgresql/data:rw
        networks:
            - symfony_network

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - symfony_network


    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        user: "0:0"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        env_file:
            - .env


    zookeeper-2:
        image: confluentinc/cp-zookeeper:latest
        user: "0:0"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 32181:2181
        env_file:
            - .env

    kafka-1:
        image: confluentinc/cp-kafka:latest
        user: "0:0"
        depends_on:
            - zookeeper-1
            - zookeeper-2
        ports:
            - 29092:29092
        env_file:
            - .env
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


    kafka-2:
        image: confluentinc/cp-kafka:latest
        user: "0:0"
        depends_on:
            - zookeeper-1
            - zookeeper-2
        ports:
            - 39092:39092
        env_file:
            - .env
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - 8082:8080
        environment:
            DYNAMIC_CONFIG_ENABLED: true

networks:
    symfony_network:
        driver: bridge

volumes:
    data-pgsql:
        driver: local
    redis:
        driver: local
